7


SELECT dist_permiso FROM usuarios WHERE id = $id_usuario


SELECT a.CANT_SUPERVISOR_TIGO, a.CANT_DISTRIBUIDOR, a.CANT_RUTAS, a.TOTAL, a.DESABASTECIDO,a.IND_DESABASTECIDO
        FROM BD_JEFETIGO_DESABASTECIDO_INDICE_30MIN a
        INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
        WHERE a.ID_JEFE_TIGO  in (4);





SELECT DISTINCT a.ID_ZONA, z.ZONA FROM BD_JEFETIGO_ZONA_DESABASTECIDO_INDICE_30MIN a
    INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
    INNER JOIN ITC_CATALOGOS..CTG_ID_ZONA z on z.ID_ZONA = a.ID_ZONA
    WHERE a.ID_JEFE_TIGO in  (4) AND a.DESABASTECIDO > 0
    ORDER BY z.ZONA ASC;






SELECT a.CANT_SUPERVISOR_TIGO, a.CANT_DISTRIBUIDOR, a.CANT_RUTAS,a.TOTAL, a.DESABASTECIDO,a.IND_DESABASTECIDO  FROM BD_JEFETIGO_ZONA_DESABASTECIDO_INDICE_30MIN a
        INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
        INNER JOIN ITC_CATALOGOS..CTG_ID_ZONA z on z.ID_ZONA = a.ID_ZONA
        WHERE a.ID_ZONA in ($z) and a.ID_JEFE_TIGO in (4);





SELECT a.ID_SUPV_TIGO, s.NOM_SUPV_TIGO  FROM BD_SUPVTIGO_COMPLETA_ZONA_DESABASTECIDO_INDICE_30MIN a
    INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
    INNER JOIN ITC_CATALOGOS..CTG_ID_ZONA z on z.ID_ZONA = a.ID_ZONA
    INNER JOIN ITC_CATALOGOS..CTG_ID_SUPERVISOR_TIGO s on s.ID_SUPV_TIGO = a.ID_SUPV_TIGO
    WHERE a.ID_ZONA in ($z) and a.ID_JEFE_TIGO in (4) AND a.DESABASTECIDO > 0
    ORDER BY s.NOM_SUPV_TIGO ASC;



SELECT  a.TOTAL, a.DESABASTECIDO, a.IND_DESABASTECIDO  FROM BD_SUPVTIGO_COMPLETA_ZONA_DESABASTECIDO_INDICE_30MIN a
    INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
    INNER JOIN ITC_CATALOGOS..CTG_ID_ZONA z on z.ID_ZONA = a.ID_ZONA
    INNER JOIN ITC_CATALOGOS..CTG_ID_SUPERVISOR_TIGO s on s.ID_SUPV_TIGO = a.ID_SUPV_TIGO
    WHERE a.ID_SUPV_TIGO in ($m) and a.ID_ZONA in ($z) and a.ID_JEFE_TIGO in (4);


SELECT a.ID_RUTA_ITC AS id,a.ID_ZONA, a.NOMBRE_RUTA,a.NOMBRE_DEL_DISTRIBUIDOR, a.COORDINADOR, a.SUPERVISOR,a.TOTAL, a.DESABASTECIDO, a.IND_DESABASTECIDO
      FROM BD_SUPV_JEFE_TIGO_COMPLETA_X_RUTA_X_ZONA_DESABASTECIDO_INDICE_30MIN a
      INNER JOIN ITC_CATALOGOS..CTG_ID_JEFE_TIGO c on c.ID_JEFE_TIGO = a.ID_JEFE_TIGO
      INNER JOIN ITC_CATALOGOS..CTG_ID_ZONA z on z.ID_ZONA = a.ID_ZONA
      INNER JOIN ITC_CATALOGOS..CTG_ID_SUPERVISOR_TIGO s on s.ID_SUPV_TIGO = a.ID_SUPV_TIGO
      WHERE a.DESABASTECIDO > 0 and  a.ID_SUPV_TIGO in ($m) and a.ID_ZONA in ($z) and a.ID_JEFE_TIGO in (4)